services:
  web:
    build: .
    ports:
      - "8008:8000"
    volumes:
      - ./app:/code/app
      - ./tests:/code/tests
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - ./.env
    environment:
      - PYTHONPATH=/code
